# Generated by Django 4.0.4 on 2022-04-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_message',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
