# Generated by Django 4.0.4 on 2022-04-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_message_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='message',
            field=models.TextField(blank=True, max_length=255, verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='chat_message',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='ルーム'),
        ),
    ]
