# Generated by Django 4.0.4 on 2022-04-21 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_message',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
